### ISSUE TITLE
How to customize / modify the default CSS used by `ox-html`

### ISSUE THREAD

**Issue by Nathan-Furnal** [ox-tufte/ox-tufte#27]
Hey, 

This is a question since the issue lies with org-mode. When exporting, the default CSS shipped with ox-html inserts: 

``` css
  pre {
    border: 1px solid #e6e6e6;
    border-radius: 3px;
    background-color: #f2f2f2;
    padding: 8pt;
    font-family: monospace;
    overflow: auto;
    margin: 1.2em;
  }
```

This background color is problematic since when the page is viewed under dark mode, you get something illegible like: 
![image](https://github.com/user-attachments/assets/bab966b5-f827-48e0-a3b4-572caadaac26)

As you can see, the background color is hard-coded (simply removing it solves the issue). There is actually a bunch of hard-coded color in the default CSS. 

Do you think it is something your package could or should address? If not, what do you think I could use to fix it? I'm not sure where to define that CSS. 

Thanks for thelp.

- org version 9.7.11
- Emacs 29.4
- latest version of both tufte.css and ox-tufte.css as of September 2024.

**Comment by dakrone** [comment]
I took the background color from the Tufte files, so I assume they are the ones that hardcoded the background color. Is the dark background something that the Tufte CSS is doing, or is that a customization or yours?

**Comment by suhail-singh** [comment]
@Nathan-Furnal thank you for the detailed report.  I'll summarize my
understanding below before sharing my recommendation.  Please correct me in case
I have misunderstood.

The current defaults of `ox-html` hard-codes the value of `background-color`.
Doing so interferes with "dark mode".  Removing the `background-color`
specification from `pre` resolves the issue.

> Do you think it is something your package could or should address?

No, I believe this is outside the scope of `ox-tufte`.

> If not, what do you think I could use to fix it? I'm not sure where to define
> that CSS.

If my understanding is correct, one way to fix it would be to override the
`background-color` specification.  For this there are a few options (in no
particular order, and untested):

1. Add custom CSS to the page using [the `prefers-color-scheme` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).
   Something like (the CSS selector may need to be tweaked):
   ```css
   @media (prefers-color-scheme: dark) {
     pre {
       background-color: unset !important;
     }
   }
   ```

2. Customize the value of `org-html-style-default` as needed.  This should be
   done early in the export process (before invoking the exporter).

3. Customize the value of `org-html-htmlize-output-type` to be `'css` instead of
   `'inline-css`.  This, too, should be done early in the export process.  Doing
   so will not inline the default CSS.  This would mean that you could provide
   your own customized version of the CSS (perhaps one that is derived /
   inspired from the standard value of `org-html-style-default`), and provided
   that customized version of the CSS doesn't specify the `background-color` and
   is linked to from the HTML page (perhaps via `HTML_HEAD` or
   `HTML_HEAD_EXTRA`) things should work.

Hope that helps.

**Comment by Nathan-Furnal** [comment]
Thanks indeed this is correct from my understanding of org-mode as well. I'll try some of those fixes when I have the time!

**Comment by Nathan-Furnal** [comment]
I just added the relevant CSS from the first solution to the top of the `ox-tufte.css`, it seems to be the least intrusive answer imo.
